export const PRODUCT_CATEGORIES = [
  { value: 'accessories', label: 'Acessórios' },
  { value: 'activewear', label: 'Moda Fitness' },
  { value: 'beachwear', label: 'Moda Praia' },
  { value: 'blouses', label: 'Blusas' },
  { value: 'coats', label: 'Casacos' },
  { value: 'footwear', label: 'Calçados' },
  { value: 'shirts', label: 'Camisas' },
  { value: 'tshirts', label: 'Camisetas' },
  { value: 'sets', label: 'Conjuntos' },
  { value: 'tops', label: 'Croppeds / Tops' },
  { value: 'skirts', label: 'Saias' },
  { value: 'jackets', label: 'Jaquetas' },
  { value: 'jeans', label: 'Jeans' },
  { value: 'leggings', label: 'Leggings' },
  { value: 'lingerie', label: 'Lingerie' },
  { value: 'jumpsuits', label: 'Macacões' },
  { value: 'pants', label: 'Calças' },
  { value: 'shorts', label: 'Shorts' },
  { value: 'sweaters', label: 'Suéteres' },
  { value: 'dresses', label: 'Vestidos' },
];
