export const PRODUCT_CATEGORIES = [
  { value: 'accessories', label: 'Acessórios', code: 'AC' },
  { value: 'activewear', label: 'Moda Fitness', code: 'AF' },
  { value: 'beachwear', label: 'Moda Praia', code: 'MPR' },
  { value: 'blazers', label: 'Blazers', code: 'BLA' },
  { value: 'blouses', label: 'Blusas', code: 'BLU' },
  { value: 'bodysuits', label: 'Bodys', code: 'BOD' },
  { value: 'coats', label: 'Casacos / Sobretudos', code: 'CAS' },
  { value: 'cardigans', label: 'Cardigans', code: 'CAR' },
  { value: 'footwear', label: 'Calçados', code: 'CAL' },
  { value: 'shirts', label: 'Camisas', code: 'CAM' },
  { value: 'tshirts', label: 'Camisetas', code: 'CTS' },
  { value: 'sets', label: 'Conjuntos', code: 'CON' },
  { value: 'tops', label: 'Croppeds / Tops', code: 'TOP' },
  { value: 'skirts', label: 'Saias', code: 'SAI' },
  { value: 'jackets', label: 'Jaquetas', code: 'JAQ' },
  { value: 'jeans', label: 'Jeans', code: 'JEA' },
  { value: 'kimonos', label: 'Kimonos', code: 'KIM' },
  { value: 'leggings', label: 'Leggings', code: 'LEG' },
  { value: 'lingerie', label: 'Lingerie', code: 'LIN' },
  { value: 'loungewear', label: 'Roupas de Casa', code: 'LOU' },
  { value: 'jumpsuits', label: 'Macacões', code: 'MAC' },
  { value: 'overalls', label: 'Jardineiras', code: 'JAR' },
  { value: 'pants', label: 'Calças', code: 'PAN' },
  { value: 'sleepwear', label: 'Pijamas', code: 'PIJ' },
  { value: 'shorts', label: 'Shorts', code: 'SHO' },
  { value: 'sweaters', label: 'Suéteres / Tricots', code: 'SUE' },
  { value: 'dresses', label: 'Vestidos', code: 'VES' },
];
